### ISSUE TITLE
RuntimeException on tapping on images.

### ISSUE THREAD

**Issue by chetdeva** [ZacSweers/CatchUp#144]
The app crashes on tapping on images for say Dribble with the following stacktrace.
```
01-15 15:42:39.384 16738-16738/io.sweers.catchup.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.sweers.catchup.debug, PID: 16738
    java.lang.RuntimeException: Unable to start activity ComponentInfo{io.sweers.catchup.debug/io.sweers.catchup.ui.activity.ImageViewerActivity}: android.view.InflateException: Binary XML file line #46: Binary XML file line #46: Error inflating class com.google.android.material.bottomappbar.BottomAppBar
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3000)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3078)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:187)
        at android.app.ActivityThread.main(ActivityThread.java:7025)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:514)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:888)
     Caused by: android.view.InflateException: Binary XML file line #46: Binary XML file line #46: Error inflating class com.google.android.material.bottomappbar.BottomAppBar
     Caused by: android.view.InflateException: Binary XML file line #46: Error inflating class com.google.android.material.bottomappbar.BottomAppBar
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
        at android.view.LayoutInflater.createView(LayoutInflater.java:650)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:797)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:737)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:870)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:831)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:469)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:141)
        at io.sweers.catchup.ui.activity.ImageViewerActivity.onCreate(ImageViewerActivity.kt:111)
        at android.app.Activity.performCreate(Activity.java:7290)
        at android.app.Activity.performCreate(Activity.java:7281)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2953)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3078)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:187)
        at android.app.ActivityThread.main(ActivityThread.java:7025)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:514)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:888)
     Caused by: java.lang.IllegalArgumentException: The style on this component requires your app theme to be Theme.MaterialComponents (or a descendant).
        at com.google.android.material.internal.ThemeEnforcement.checkTheme(ThemeEnforcement.java:240)
        at com.google.android.material.internal.ThemeEnforcement.checkMaterialTheme(ThemeEnforcement.java:215)
        at com.google.android.material.internal.ThemeEnforcement.checkCompatibleTheme(ThemeEnforcement.java:143)
        at com.google.android.material.internal.ThemeEnforcement.obtainStyledAttributes(ThemeEnforcement.java:78)
        at com.google.android.material.bottomappbar.BottomAppBar.<init>(BottomAppBar.java:223)
        at com.google.android.material.bottomappbar.BottomAppBar.<init>(BottomAppBar.java:214)
        at java.lang.reflect.Constructor.newInstance0(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:334) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:650) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:797) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:737) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:870) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:831) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:469) 
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:141) 
        at io.sweers.catchup.ui.activity.ImageViewerActivity.onCreate(ImageViewerActivity.kt:111) 
        at android.app.Activity.performCreate(Activity.java:7290) 
        at android.app.Activity.performCreate(Activity.java:7281) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2953) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3078) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:187) 
        at android.app.ActivityThread.main(ActivityThread.java:7025) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:514) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:888) 
```

**Comment by ZacSweers** [comment]
Is this a debug build?

**Comment by ZacSweers** [comment]
Closing as this I haven't been able to reproduce it
