### ISSUE TITLE
Debug crashes on start: java.lang.RuntimeException: Timber e! Please fix:

### ISSUE THREAD

**Issue by jaredsburrows** [ZacSweers/CatchUp#156]
## Repo:
`gradlew installDebug`

## Error:
```
06-07 20:42:52.402 14590 14590 E FontHelper$load$callback: Font download failed with reason 2
06-07 20:42:52.404 14590 14590 D AndroidRuntime: Shutting down VM
06-07 20:42:52.407 14590 14590 E AndroidRuntime: FATAL EXCEPTION: main
06-07 20:42:52.407 14590 14590 E AndroidRuntime: Process: io.sweers.catchup.debug, PID: 14590
06-07 20:42:52.407 14590 14590 E AndroidRuntime: java.lang.RuntimeException: Timber e! Please fix:
06-07 20:42:52.407 14590 14590 E AndroidRuntime: Tag=null
06-07 20:42:52.407 14590 14590 E AndroidRuntime: Message=Font download failed with reason 2
06-07 20:42:52.407 14590 14590 E AndroidRuntime: 	at io.sweers.catchup.app.DebugCatchUpApplication$initVariant$7.log(DebugCatchUpApplication.kt:149)
06-07 20:42:52.407 14590 14590 E AndroidRuntime: 	at timber.log.Timber$Tree.prepareLog(Timber.java:532)
06-07 20:42:52.407 14590 14590 E AndroidRuntime: 	at timber.log.Timber$Tree.e(Timber.java:450)
06-07 20:42:52.407 14590 14590 E AndroidRuntime: 	at timber.log.Timber$1.e(Timber.java:306)
06-07 20:42:52.407 14590 14590 E AndroidRuntime: 	at timber.log.Timber.e(Timber.java:83)
06-07 20:42:52.407 14590 14590 E AndroidRuntime: 	at io.sweers.catchup.ui.FontHelper$load$callback$1.onTypefaceRequestFailed(FontHelper.kt:74)
06-07 20:42:52.407 14590 14590 E AndroidRuntime: 	at androidx.core.provider.FontsContractCompat$4$7.run(FontsContractCompat.java:622)
06-07 20:42:52.407 14590 14590 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
06-07 20:42:52.407 14590 14590 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
06-07 20:42:52.407 14590 14590 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
06-07 20:42:52.407 14590 14590 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7116)
06-07 20:42:52.407 14590 14590 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-07 20:42:52.407 14590 14590 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
06-07 20:42:52.407 14590 14590 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:925)
06-07 20:42:52.416   917  5545 W ActivityTaskManager:   Force finishing activity io.sweers.catchup.debug/io.sweers.catchup.ui.activity.MainActivity
06-07 20:42:52.416   917 14675 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
```
and
```
06-07 20:45:30.032   917  1017 W ActivityTaskManager: Activity top resumed state loss timeout for ActivityRecord{e930667 u0 io.sweers.catchup.debug/io.sweers.catchup.ui.activity.MainActivity t-1 f}
06-07 20:45:30.622  2350  2368 E FontsContentProvider: Fetch {Nunito, wdth 100.0, wght 400, ital 0.0, bestEffort false} failed due to timeout
06-07 20:45:30.622  2350  2368 E FontsContentProvider: java.util.concurrent.TimeoutException: Waited 10000 milliseconds (plus 320944 nanoseconds delay) for bpik@11a5efe[status=PENDING]
06-07 20:45:30.622  2350  2368 E FontsContentProvider: 	at bpfa.get(:com.google.android.gms@17455037@17.4.55 (100400-248795830):55)
06-07 20:45:30.622  2350  2368 E FontsContentProvider: 	at bpfk.get(Unknown Source:0)
06-07 20:45:30.622  2350  2368 E FontsContentProvider: 	at zyl.query(:com.google.android.gms@17455037@17.4.55 (100400-248795830):9)
06-07 20:45:30.622  2350  2368 E FontsContentProvider: 	at qbz.query(:com.google.android.gms@17455037@17.4.55 (100400-248795830):3)
06-07 20:45:30.622  2350  2368 E FontsContentProvider: 	at android.content.ContentProvider.query(ContentProvider.java:1204)
06-07 20:45:30.622  2350  2368 E FontsContentProvider: 	at ecd.superQuery(:com.google.android.gms@17455037@17.4.55 (100400-248795830):2)
06-07 20:45:30.622  2350  2368 E FontsContentProvider: 	at com.google.android.chimera.ContentProvider.query(:com.google.android.gms@17455037@17.4.55 (100400-248795830):2)
06-07 20:45:30.622  2350  2368 E FontsContentProvider: 	at qbz.query(:com.google.android.gms@17455037@17.4.55 (100400-248795830):12)
06-07 20:45:30.622  2350  2368 E FontsContentProvider: 	at android.content.ContentProvider.query(ContentProvider.java:1297)
06-07 20:45:30.622  2350  2368 E FontsContentProvider: 	at ecd.superQuery(:com.google.android.gms@17455037@17.4.55 (100400-248795830):1)
06-07 20:45:30.622  2350  2368 E FontsContentProvider: 	at com.google.android.chimera.ContentProvider.query(:com.google.android.gms@17455037@17.4.55 (100400-248795830):1)
06-07 20:45:30.622  2350  2368 E FontsContentProvider: 	at ecd.query(:com.google.android.gms@17455037@17.4.55 (100400-248795830):3)
06-07 20:45:30.622  2350  2368 E FontsContentProvider: 	at android.content.ContentProvider$Transport.query(ContentProvider.java:267)
06-07 20:45:30.622  2350  2368 E FontsContentProvider: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:104)
06-07 20:45:30.622  2350  2368 E FontsContentProvider: 	at android.os.Binder.execTransactInternal(Binder.java:1021)
06-07 20:45:30.622  2350  2368 E FontsContentProvider: 	at android.os.Binder.execTransact(Binder.java:994)
```

**Comment by ZacSweers** [comment]
Do you have an internet connection? Looks like fonts and gms both couldn't download

**Comment by jaredsburrows** [comment]
Yes. I am using other applications that use internet just fine.

**Comment by ZacSweers** [comment]
Not sure, maybe just gms was having issues then since font downloads happen
through it as well. It's just a debug error in any case, so going to close
this for now. In prod it would gracefully fall back to default fonts.
