### ISSUE TITLE
Debug build works, but release build fails to start

### ISSUE THREAD

**Issue by sid-maddy** [ZacSweers/CatchUp#236]
# Installation steps
1. `git clone git@github.com:ZacSweers/CatchUp.git`
2. `cd CatchUp`
2. `echo "sdk.dir=/usr/lib/android-sdk" > local.properties`
3. `./gradlew installRelease`

## [Crash Log](https://del.dog/nugnallove)
```
time: 1594386913994
msg: java.lang.ClassNotFoundException: Didn't find class "dev.zacsweers.ticktock.android.lazyzonerules.startup.AndroidLazyZoneRulesInitializer" on path: DexPathList[[zip file "/data/app/io.sweers.catchup-vOQio_3L3cZN8MzBQyxceA==/base.apk"],nativeLibraryDirectories=[/data/app/io.sweers.catchup-vOQio_3L3cZN8MzBQyxceA==/lib/arm64, /data/app/io.sweers.catchup-vOQio_3L3cZN8MzBQyxceA==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
stacktrace: java.lang.RuntimeException: Unable to get provider androidx.startup.InitializationProvider: n0.x.d: java.lang.ClassNotFoundException: dev.zacsweers.ticktock.android.lazyzonerules.startup.AndroidLazyZoneRulesInitializer
	at android.app.ActivityThread.installProvider(ActivityThread.java:6451)
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:5993)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5908)
	at android.app.ActivityThread.access$1100(ActivityThread.java:201)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1657)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6724)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: n0.x.d: java.lang.ClassNotFoundException: dev.zacsweers.ticktock.android.lazyzonerules.startup.AndroidLazyZoneRulesInitializer
	at androidx.startup.InitializationProvider.onCreate(InitializationProvider.java:23)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:1921)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:1896)
	at android.app.ActivityThread.installProvider(ActivityThread.java:6446)
	... 10 more
Caused by: java.lang.ClassNotFoundException: dev.zacsweers.ticktock.android.lazyzonerules.startup.AndroidLazyZoneRulesInitializer
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:453)
	at java.lang.Class.forName(Class.java:378)
	at androidx.startup.InitializationProvider.onCreate(InitializationProvider.java:19)
	... 13 more
Caused by: java.lang.ClassNotFoundException: Didn't find class "dev.zacsweers.ticktock.android.lazyzonerules.startup.AndroidLazyZoneRulesInitializer" on path: DexPathList[[zip file "/data/app/io.sweers.catchup-vOQio_3L3cZN8MzBQyxceA==/base.apk"],nativeLibraryDirectories=[/data/app/io.sweers.catchup-vOQio_3L3cZN8MzBQyxceA==/lib/arm64, /data/app/io.sweers.catchup-vOQio_3L3cZN8MzBQyxceA==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 17 more
```

**Comment by ZacSweers** [comment]
That's strange, androidx.startup [includes rules](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-master-dev:startup/startup-runtime/proguard-rules.pro) that should keep that class. I'll file an issue over there (CC @tikurahul)

**Comment by tikurahul** [comment]
Fixed in `alpha02`. We defined the rules but we forgot to apply them.

**Comment by ZacSweers** [comment]
ahhhh that'll do it 😛 . I'll close this out then
