### ISSUE TITLE
StrictMode issue from Stetho

### ISSUE THREAD

**Issue by ZacSweers** [ZacSweers/CatchUp#94]
Corresponds to https://github.com/facebook/stetho/issues/379

Going to see if they're open to a PR

```
D/StrictMode: StrictMode policy violation; ~duration=89 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=65599 violation=2
                                                                         at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1440)
                                                                         at libcore.io.BlockGuardOs.read(BlockGuardOs.java:250)
                                                                         at libcore.io.IoBridge.read(IoBridge.java:528)
                                                                         at java.io.FileInputStream.read(FileInputStream.java:254)
                                                                         at java.io.FileInputStream.read(FileInputStream.java:228)
                                                                         at com.facebook.stetho.common.ProcessUtil.readProcessName(ProcessUtil.java:52)
                                                                         at com.facebook.stetho.common.ProcessUtil.getProcessName(ProcessUtil.java:38)
                                                                         at com.facebook.stetho.server.AddressNameHelper.createCustomAddress(AddressNameHelper.java:20)
                                                                         at com.facebook.stetho.Stetho$Initializer.start(Stetho.java:449)
                                                                         at com.facebook.stetho.Stetho.initialize(Stetho.java:134)
                                                                         at com.facebook.stetho.Stetho.initializeWithDefaults(Stetho.java:105)
                                                                         at io.sweers.catchup.app.DebugCatchUpApplication.initVariant(DebugCatchUpApplication.kt:65)
                                                                         at io.sweers.catchup.app.CatchUpApplication.onCreate(CatchUpApplication.kt:64)
```

**Comment by hzsweers** [comment]
Stetho appears abandoned, not much I can do for now

**Comment by faogustavo** [comment]
@ZacSweers looks like facebook decided to invest in [Flipper](https://github.com/facebook/flipper) instead. What do you think about changing the library?

**Comment by ZacSweers** [comment]
Yeah it's probably about time to ditch it, though I haven't been thrilled with the stability of Flipper's releases. It's very obviously under the category of "disclosed source" rather than open source, and releases have been completely broken a number of times with very slow followups to address them
